fixes : add code for ams
cap-js/calesi pull request #33
Opened 2023-10-26 08:23 UTC by singhabhi1999

2023-10-26 08:48 UTC, danjoa approved these changes

2023-10-26 18:09 UTC, sjvans requested changes
see https://github.com/cap-js/calesi/pull/36

2023-10-27 07:05 UTC, sjvans approved these changes

2023-10-29 12:21 UTC, sjvans approved these changes
lgtm

2023-10-29 12:37 UTC, sjvans commented on .gitignore
> +samples/ams/ams
```suggestion
!plugins/notifications

samples/ams/ams
```

2023-11-10 10:37 UTC, merged